cards = [
  {"gr": "το μαυρο",
   "en": "the black",
   "level": 0,
   "constructions": ["present"],
   "gr_ex": [
     {"present":["το μαύρο σπίτι",
                 "το μαύρο μάθημα",
                 "το μαύρο θέατρο",
                 "το μαύρο σκυλί",
                 "ο μαύρος δρόμος",
                 "ο μαύρος",
                 "ο μαύρος πατέρας",
                 "ο μαύρος θεός",
                 "η μαύρη γυναίκα",
                 "η μαύρη Ελένη",
                 "η μαύρη μητέρα",
                 "η μαύρη θεά"
     ]},
   ],
   "en_ex": [
     {"present":["the black home",
                 "the black lesson",
                 "the black theater",
                 "the black dog",
                 "the black road",
                 "the black man",
                 "the black father",
                 "the black god",
                 "the black woman",
                 "the black Helen",
                 "the black mother",
                 "the black goddess"
     ]},
   ],
   "ctable": [
   ],
   "img":"decks/black.jpg"},
  {"gr": "το λευκό / το άσπρος",
   "en": "the white",
   "level": 0,
   "constructions": ["present"],
   "gr_ex": [
    {"present":["το λευκό / άσπρο σπίτι",
                "το λευκό / άσπρο μάθημα",
                "το λευκό / άσπρο θέατρο",
                "το λευκό / άσπρο κυλί",
                "ο λευκός / άσπρος δρόμος",
                "ο λευκός",
                "ο λευκός / άσπρος πατέρας",
                "ο λευκός / άσπρος θεός",
                "η λευκή / άσπρή γυναίκα",
                "η λευκή / άσπρή Ελένη",
                "η λευκή / άσπρή μητέρα",
                "η λευκή / άσπρή θεά",
                "το λευκό κρασί"
    ]},
   ],
   "en_ex": [
    {"present":["the white home",
                "the white lesson",
                "the white theater",
                "the white dog",
                "the white road",
                "the white man",
                "the white father",
                "the white god",
                "the white woman",
                "the white Helen",
                "the white mother",
                "the white goddess",
                "the white wine"
    ]},
   ],
   "ctable": [
   ],
   "img":"decks/white.jpg"},
   {"gr": "το λευκό / το άσπρος",
    "en": "the white",
    "level": 0,
    "constructions": ["present"],
    "gr_ex": [
     {"present":["το λευκό / άσπρο σπίτι",
                 "το λευκό / άσπρο μάθημα",
                 "το λευκό / άσπρο θέατρο",
                 "το λευκό / άσπρο κυλί",
                 "ο λευκός / άσπρος δρόμος",
                 "ο λευκός",
                 "ο λευκός / άσπρος πατέρας",
                 "ο λευκός / άσπρος θεός",
                 "η λευκή / άσπρή γυναίκα",
                 "η λευκή / άσπρή Ελένη",
                 "η λευκή / άσπρή μητέρα",
                 "η λευκή / άσπρή θεά",
                 "το λευκό κρασί"
     ]},
    ],
    "en_ex": [
     {"present":["the white home",
                 "the white lesson",
                 "the white theater",
                 "the white dog",
                 "the white road",
                 "the white man",
                 "the white father",
                 "the white god",
                 "the white woman",
                 "the white Helen",
                 "the white mother",
                 "the white goddess",
                 "the white wine"
     ]},
    ],
    "ctable": [
    ],
    "img":"decks/white.jpg"},
 ]
nextCard();